# -*- coding: utf-8 -*-
"""Automatic Email Reply (Fixed)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxc0c6-EH0DDtX1dX7-i5E_mgOPNr9F2
"""

from flask import Flask, request, jsonify
# Import T5 models instead of BART for generation
from transformers import T5Tokenizer, T5ForConditionalGeneration, pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from pathlib import Path
import numpy as np
import csv
import torch
import os
import time # For logging approved replies

app = Flask(__name__)

# --- IN-MEMORY DATABASE ---
db = {
    "drafts": {},
    "reply_logs": [],
    "settings": {"signature": "Best regards,\nYour Name"},
    "sender_rules": {
        "ceo@company.com": "formal",
        "friend@gmail.com": "friendly"
    }
}
draft_counter = 0

# --- MODEL CONFIGURATION ---
tone_model_name = "facebook/bart-large-mnli"
reply_model_name = "google/flan-t5-base"

# --- LOAD MODELS ---
print("Loading models... This may take a moment.")
try:
    tone_classifier = pipeline("zero-shot-classification", model=tone_model_name, device=0 if torch.cuda.is_available() else -1)
except Exception as e:
    tone_classifier = None
    print(f"[WARN] Could not load tone classifier: {e}")

try:
    tokenizer = T5Tokenizer.from_pretrained(reply_model_name)
    reply_model = T5ForConditionalGeneration.from_pretrained(reply_model_name)
    if torch.cuda.is_available():
        reply_model.to("cuda")
    print("Reply model loaded successfully.")
except Exception as e:
    print(f"[FATAL] Could not load reply model '{reply_model_name}': {e}")
    tokenizer = None
    reply_model = None

# --- RAG (Retrieval) SETUP ---
ENRON_PATH = Path("./data/enron_replies.csv")
CORPUS = []

if ENRON_PATH.exists():
    print(f"Loading corpus from {ENRON_PATH}...")
    with open(ENRON_PATH, newline='', encoding='utf-8', errors='ignore') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            text = (row.get('reply') or row.get('response') or row.get('body') or '').strip()
            if text and len(text) > 20:
                CORPUS.append(text)
    print(f"Loaded {len(CORPUS)} documents.")
else:
    print(f"[WARN] Enron data not found at {ENRON_PATH}. Retrieval will be disabled.")

if CORPUS:
    VECTORIZER = TfidfVectorizer(stop_words='english', max_features=5000)
    TFIDF_MATRIX = VECTORIZER.fit_transform(CORPUS)
    print("TF-IDF matrix built.")
else:
    VECTORIZER = None
    TFIDF_MATRIX = None

TONE_LABELS = [
    "formal", "informal", "friendly", "apologetic", "persuasive", "technical",
    "neutral", "assertive", "enthusiastic", "empathetic", "directive",
    "informative", "customer_service", "urgent", "brief", "detailed"
]

# --- TONE INSTRUCTIONS (Moved to global for reuse) ---
TONE_INSTRUCTIONS = {
    "formal": "Be polite, concise, and professional.", "informal": "Be friendly, conversational, and relaxed.",
    "friendly": "Be warm, kind, and approachable.", "apologetic": "Be empathetic and include an apology if relevant.",
    "persuasive": "Be confident and convincing, with a clear call to action.", "technical": "Use clear technical explanations and factual tone.",
    "neutral": "Be objective and balanced.", "assertive": "Be confident but respectful.",
    "enthusiastic": "Sound excited and positive.", "empathetic": "Be understanding and compassionate.",
    "directive": "Be instructive and action-oriented.", "informative": "Provide detailed and relevant information.",
    "customer_service": "Be polite, reassuring, and service-focused.", "urgent": "Be concise, clear, and emphasize timeliness.",
    "brief": "Keep it under three sentences, clear and direct.", "detailed": "Provide thoughtful and thorough explanations."
}

# --- CORE AI FUNCTIONS (Your engine) ---

def predict_tone(email_text: str):
    """Predicts tone using the zero-shot classifier."""
    if not email_text.strip(): return {"error": "empty text"}
    if not tone_classifier: return {"tone": "neutral", "confidence": 0.0, "error": "Classifier not loaded"}
    try:
        result = tone_classifier(email_text, TONE_LABELS, multi_label=False)
        tone = result["labels"][0]
        confidence = result["scores"][0]
        print(f"[Tone] Detected: {tone} (Conf: {confidence:.2f})")
        return {"tone": tone, "confidence": float(confidence)}
    except Exception as e:
        print(f"[WARN] HF tone inference failed: {e}")
    return {"tone": "neutral", "confidence": 0.0}

def retrieve_examples(prompt: str, k=3):
    """Retrieves k-most similar replies from the Enron corpus."""
    if TFIDF_MATRIX is None or not CORPUS: return []
    try:
        q_vec = VECTORIZER.transform([prompt])
        sims = cosine_similarity(q_vec, TFIDF_MATRIX)[0]
        idxs = np.argsort(sims)[::-1][:k]
        return [CORPUS[i] for i in idxs]
    except Exception as e:
        print(f"[WARN] TF-IDF retrieval failed: {e}")
        return []

def _generate_t5_text(prompt: str, generation_params: dict) -> list:
    """Internal helper function for T5 generation."""
    if not reply_model:
        return ["Error: Reply model is not loaded."]
    try:
        inputs = tokenizer(prompt, return_tensors="pt", max_length=1024, truncation=True)
        if torch.cuda.is_available():
            inputs = inputs.to("cuda")

        summary_ids = reply_model.generate(
            inputs["input_ids"],
            **generation_params
        )

        replies = tokenizer.batch_decode(summary_ids, skip_special_tokens=True)
        return [reply.strip() for reply in replies]
    except Exception as e:
        print(f"[FATAL] T5 generation failed: {e}")
        return [f"Error: Could not generate reply. {e}"]

# --- FIXED: Function for generating a reply ---
def generate_reply_t5(email_text: str, tone: str = "formal", k_examples: int = 3) -> str:
    """Generates a single, creative reply."""
    tone_instruction = TONE_INSTRUCTIONS.get(tone.lower(), "Be professional.")

    examples = retrieve_examples(email_text, k=k_examples)
    context = "\n\nHere are some examples of similar replies:\n" + "\n".join(f"- {ex}" for ex in examples) if examples else ""

    prompt = (
        f"You are a helpful colleague writing an email. Your goal is to write a natural, conversational reply to the email below.\n\n"
        f"**Your instructions:**\n"
        f"- Your reply must be {tone}. {tone_instruction}\n"
        f"- Start with a friendly greeting (e.g., 'Hi,', or 'Hello,').\n"
        f"- Address all the questions or points from the original email.\n"
        f"- Do not just summarize the action. Write a complete, human-sounding message.\n\n"
        f"**Original Email:**\n{email_text}\n"
        f"{context}\n\n"
        f"**Your Reply:**\n"
    )

    params = {
        "max_length": 250,
        "min_length": 15,
        "do_sample": True,
        "top_p": 0.95,
        "temperature": 0.7,
        "repetition_penalty": 1.1
    }

    return _generate_t5_text(prompt, params)[0]

# --- NEWLY SEPARATED: Function for extracting points ---
def extract_main_points_t5(email_text: str) -> str:
    """Uses T5 to extract main points from an email."""
    prompt = (
        f"INSTRUCTION: Summarize the key action items and questions from the following email. "
        f"Present them as a bulleted list.\n\n"
        f"EMAIL:\n{email_text}\n\n"
        f"SUMMARY OF POINTS:"
    )

    params = {
        "max_length": 150,
        "min_length": 10,
        "num_beams": 3,
        "early_stopping": True
    }
    return _generate_t5_text(prompt, params)[0]

# --- FIXED: Function for generating variants ---
def generate_reply_variants_t5(email_text: str, tone: str, k_examples: int = 2) -> list:
    """Generates multiple reply variants (3) using beam search."""
    tone_instruction = TONE_INSTRUCTIONS.get(tone.lower(), "Be professional.")

    examples = retrieve_examples(email_text, k=k_examples)
    context = "\n\nHere are some examples of similar replies:\n" + "\n".join(f"- {ex}" for ex in examples) if examples else ""

    prompt = (
        f"INSTRUCTION: Write a {tone} email reply to the following email. {tone_instruction}\n\n"
        f"EMAIL:\n{email_text}\n"
        f"{context}\n\n"
        f"REPLY:"
    )

    params = {
        "max_length": 200,
        "min_length": 15,
        "num_beams": 5,
        "num_return_sequences": 3,
        "early_stopping": True,
        "repetition_penalty": 1.2
    }
    return _generate_t5_text(prompt, params)


# --- FLASK API ENDPOINTS (Now correctly calling functions) ---

# 1. POST /parse_email
@app.route("/parse_email", methods=["POST"])
def parse_email_api():
    """Extracts main points from raw email text using T5."""
    data = request.get_json(force=True)
    text = data.get("email_text", "").strip()
    if not text:
        return jsonify({"error": "email_text is required"}), 400

    points = extract_main_points_t5(text)
    return jsonify({"main_points": points})

# 2. POST /generate_reply (with Agent)
@app.route("/generate_reply", methods=["POST"])
def generate_reply_api():
    """Generates an AI reply using the agent-driven pipeline."""
    global draft_counter
    data = request.get_json(force=True)
    text = data.get("email_text", "").strip()
    sender = data.get("sender", "").strip()

    if not text:
        return jsonify({"error": "email_text is required"}), 400

    # --- AGENT LOGIC ---
    tone = db["sender_rules"].get(sender)
    if not tone:
        print(f"[Agent] No rule for {sender}. Predicting tone...")
        tone_data = predict_tone(text)
        tone = tone_data.get("tone", "neutral")
    else:
        print(f"[Agent] Found rule for {sender}. Using tone: {tone}")
    # --- END AGENT LOGIC ---

    reply = generate_reply_t5(text, tone) # Now calls the correct reply function

    draft_counter += 1
    draft_id = draft_counter
    draft = {
        "id": draft_id, "sender": sender, "email_text": text,
        "reply_text": reply, "tone": tone, "status": "draft",
        "created_at": time.time()
    }
    db["drafts"][draft_id] = draft

    return jsonify(draft), 201

# 3. POST /set_tone (Agent Training)
@app.route("/set_tone", methods=["POST"])
def set_tone_api():
    """Sets a specific tone for a sender (trains the agent)."""
    data = request.get_json(force=True)
    sender = data.get("sender", "").strip()
    tone = data.get("tone", "").strip()

    if not sender or not tone:
        return jsonify({"error": "sender and tone are required"}), 400

    if tone not in TONE_LABELS:
        return jsonify({"error": f"Invalid tone. Must be one of: {TONE_LABELS}"}), 400

    db["sender_rules"][sender] = tone
    return jsonify({"message": f"Rule set: Sender '{sender}' will now use tone '{tone}'."})

# 4. GET /saved_replies
@app.route("/saved_replies", methods=["GET"])
def get_saved_replies():
    """Returns all currently saved draft replies."""
    return jsonify(list(db["drafts"].values()))

# 5. POST /approve_reply
@app.route("/approve_reply", methods=["POST"])
def approve_reply_api():
    """Marks a reply as approved, adds signature, and logs it."""
    data = request.get_json(force=True)
    try:
        reply_id = int(data.get("reply_id"))
    except (TypeError, ValueError):
        return jsonify({"error": "reply_id (integer) is required"}), 400

    draft = db["drafts"].pop(reply_id, None)

    if not draft:
        return jsonify({"error": f"Draft reply with id {reply_id} not found."}), 404

    signature = db["settings"]["signature"]
    draft["final_text"] = f"{draft['reply_text']}\n\n{signature}"
    draft["status"] = "approved"
    draft["approved_at"] = time.time()

    db["reply_logs"].append(draft)
    return jsonify(draft)

# 6. POST /reply_variants
@app.route("/reply_variants", methods=["POST"])
def reply_variants_api():
    """Generates multiple reply options."""
    data = request.get_json(force=True)
    text = data.get("email_text", "").strip()
    tone = data.get("tone", None)

    if not text:
        return jsonify({"error": "email_text is required"}), 400

    if not tone:
        tone_data = predict_tone(text)
        tone = tone_data.get("tone", "formal")

    variants = generate_reply_variants_t5(text, tone)
    return jsonify({"tone": tone, "variants": variants})

# 7. POST /add_signature
@app.route("/add_signature", methods=["POST"])
def add_signature_api():
    """Sets or updates the global email signature."""
    data = request.get_json(force=True)
    signature = data.get("signature")
    if signature is None:
        return jsonify({"error": "signature is required"}), 400

    db["settings"]["signature"] = signature
    return jsonify({"message": "Signature updated successfully.", "signature": signature})

# 8. GET /reply_history/
@app.route("/reply_history/", methods=["GET"])
def get_reply_history():
    """Fetches all approved reply logs."""
    return jsonify(db["reply_logs"])


if __name__ == "__main__":
    if not tone_classifier or not reply_model:
        print("\n[ERROR] One or more models failed to load. Exiting.")
    else:
        print("\nAll models loaded. Starting Flask server...")
        app.run(debug=False, port=5001)